baseURL = "https://bit-chaser.github.io/"
languageCode = "en-us"
title = "bit-chaser"
theme = "PaperMod"
[params]
  author = 'Nick Selpa'
  description = 'A blog built using Hugo, GitHub Actions, and GitHub Pages.'
