baseURL = "https://bit-chaser.github.io/"
languageCode = "en-us"
title = "Bit-chaser"
theme = "m10c"
[params]
  author = 'Nick Selpa'
  description = 'A blog built using Hugo, GitHub Actions, and GitHub Pages.'